[package]
name = "getmemsd"
version = "0.1.0"
authors = ["Samuel Čavoj <samuel@cavoj.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
number_prefix = "0.4"
zbus = { version = "2.0.0-beta.3", features = ["xml"] }
